<a href="https://colab.research.google.com/github/Venkat458/assignments/blob/main/Numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a function so that the columns of the output matrix are powers of the input vector.                                   
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.                                       
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.


In [1]:
import numpy as np

In [2]:
y=np.array([1,2,3,4])

In [3]:
#np.column_stack((y,y))

In [4]:
#N=3
#np.column_stack([y**(N-i-1) for i in range(N)])

In [5]:
def col_stack(in1,in2,in3):
    #in1 is input array,in2 is N value,in3 is boolean if increasing is false or true.
    N=in2
    if in3==True:
        return np.column_stack([in1**i for i in range(N)])
    else:
        return np.column_stack([in1**(N-i-1) for i in range(N) ])

col_stack(y,6,True)

array([[   1,    1,    1,    1,    1,    1],
       [   1,    2,    4,    8,   16,   32],
       [   1,    3,    9,   27,   81,  243],
       [   1,    4,   16,   64,  256, 1024]])

In [6]:
col_stack(y,4,False)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.                                                                  
The moving averages with k=4 of a ten-value sequence (n=10) is shown below i 1 2 3 4 5 6 7 8 9 10                                
===== == == == == == == == == == ==                                                                                            
Input 10 20 30 40 50 60 70 80 90 100                                                                                          
y1 25 = (10+20+30+40)/4                                                                                                
y2 35 = (20+30+40+50)/4                                                                                                            
y3 45 = (30+40+50+60)/4                                                                                                       
y4 55 = (40+50+60+70)/4                                                                                                             
y5 65 = (50+60+70+80)/4                                                                                                       
y6 75 = (60+70+80+90)/4                                                                                                          
y7 85 = (70+80+90+100)/4                                                                                                           
Thus, the moving average sequence has n-k+1=10-4+1=7 values.                                                                     
Question: Write a function to find moving average in an array over a window:                                                      
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.                    

In [7]:
n=13
k=3
sequence=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

In [8]:
def moving_averages(n,k,sequence):
    averages=[]
    for i in range(0,n-k+1):
        #print(i)
        print(sequence[i:i+k],np.mean(sequence[i:i+k]))
        averages.append(np.mean(sequence[i:i+k]))
    return np.array(averages)    
        
        
        
moving_averages(n,k,sequence)

[3 5 7] 5.0
[5 7 2] 4.666666666666667
[7 2 8] 5.666666666666667
[ 2  8 10] 6.666666666666667
[ 8 10 11] 9.666666666666666
[10 11 65] 28.666666666666668
[11 65 72] 49.333333333333336
[65 72 81] 72.66666666666667
[72 81 99] 84.0
[ 81  99 100] 93.33333333333333
[ 99 100 150] 116.33333333333333


array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])